#ifndef CALC_TOKEN_H
#define CALC_TOKEN_H

enum TokenType {
    TOKEN_TYPE_NUMBER,
    TOKEN_TYPE_OPERATOR_ADD,
    TOKEN_TYPE_OPERATOR_SUB,
    TOKEN_TYPE_OPERATOR_MUL,
    TOKEN_TYPE_OPERATOR_DIV,
    TOKEN_TYPE_OPERATOR_NEG,
    TOKEN_TYPE_BRACKET_LEFT_SMALL,
    TOKEN_TYPE_BRACKET_RIGHT_SMALL,
    TOKEN_TYPE_BRACKET_LEFT_MEDIUM,
    TOKEN_TYPE_BRACKET_RIGHT_MEDIUM,
    TOKEN_TYPE_BRACKET_LEFT_LARGE,
    TOKEN_TYPE_BRACKET_RIGHT_LARGE
};

struct Token {
    TokenType type;
    double value;
};

#endif
